language: objective-c
cache: cocoapods

os: osx
osx_image: xcode8

env:
  global:
    - XCWORKSPACE="AlamoFuzi.xcworkspace"
  matrix:
    - DESTINATION="arch=x86_64"                    SDK="macosx10.12"          SCHEME="AlamoFuzi.macOS"
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SDK="iphonesimulator10.0"  SCHEME="AlamoFuzi.iOS"
    - DESTINATION="OS=10.0,name=Apple TV 1080p"    SDK="appletvsimulator10.0" SCHEME="AlamoFuzi.tvOS"
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm" SDK="watchsimulator3.0"    SCHEME="AlamoFuzi.watchOS"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - instruments -s devices
  - set -o pipefail
  - xcodebuild -workspace "$XCWORKSPACE" -scheme "$SCHEME" -sdk $SDK build | xcpretty
