language: objective-c

os: osx
osx_image: xcode8

env:
  global:
    - XCWORKSPACE="AlamoFuzi.xcworkspace"
  matrix:
    - DESTINATION="platform=macOS,arch=x86_64" SDK="macosx10.12" ACTION="build" SCHEME="AlamoFuzi.macOS"
    - DESTINATION="platform=iOS Simulator,name=iPhone 7" SDK="iphonesimulator10.0" ACTION="build" SCHEME="AlamoFuzi.iOS"
    - DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p" SDK="appletvsimulator" ACTION="build" SCHEME="AlamoFuzi.tvOS"
    - DESTINATION="name=Apple Watch - 38mm" SDK="watchsimulator" ACTION="build" SCHEME="AlamoFuzi.watchOS"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list
  - xcodebuild -workspace "$XCWORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -sdk $SDK $ACTION | xcpretty
