language: objective-c
cache: cocoapods

os: osx
osx_image: xcode8

env:
  global:
    - XCWORKSPACE="AlamoFuzi.xcworkspace"
  matrix:
    - DESTINATION="arch=x86_64"                    SDK="macosx10.12"          SCHEME="AlamoFuzi-OSX"
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SDK="iphonesimulator10.0"  SCHEME="AlamoFuzi-iOS"     POD_LINT="YES"
    - DESTINATION="OS=10.0,name=Apple TV 1080p"    SDK="appletvsimulator10.0" SCHEME="AlamoFuzi-tvOS"
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm" SDK="watchsimulator3.0"    SCHEME="AlamoFuzi-watchOS"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCWORKSPACE" -scheme "$SCHEME" -sdk $SDK clean build | xcpretty
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
