language: objective-c
cache: cocoapods

os: osx
osx_image: xcode8

env:
  global:
    - XCWORKSPACE="AlamoFuzi.xcworkspace"
  matrix:
    - DESTINATION="arch=x86_64"                SDK="macosx10.12"          SCHEME="AlamoFuzi.macOS"
    - DESTINATION="OS=10.0,name=iPhone 7 Plus" SDK="iphonesimulator10.0"  SCHEME="AlamoFuzi.iOS"
    - DESTINATION="generic/platform=tvOS"      SDK="appletvsimulator10.0" SCHEME="AlamoFuzi.tvOS"
    - DESTINATION="generic/platform=watchOS"   SDK="watchsimulator3.0"    SCHEME="AlamoFuzi.watchOS"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCWORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -sdk $SDK build | xcpretty
