os: osx
osx_image: xcode10.2

branches:
  only:
    - master
cache:cocoapods

env:
  global:
    - WORKSPACE="AlamoFuzi.xcworkspace"
  matrix:
    - DESTINATION="arch=x86_64"                              SCHEME="AlamoFuzi-OSX"
    - DESTINATION="OS=12.2,name=iPhone XS"               SCHEME="AlamoFuzi-iOS"     POD_LINT="YES"   RUN_TESTS="YES"
    - DESTINATION="OS=12.2,name=Apple TV 4K"              SCHEME="AlamoFuzi-tvOS"
    - DESTINATION="OS=5.2,name=Apple Watch Series 4 - 44mm"  SCHEME="AlamoFuzi-watchOS"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
